#ifndef ObjTypes_H
#define ObjTypes_H


#define FLOOPY_TRACKS				FLOOPY_OBJ+1
#define FLOOPY_TRACK				FLOOPY_OBJ+2
#define FLOOPY_REGION				FLOOPY_OBJ+3
#define FLOOPY_PARAMETER			FLOOPY_OBJ+4
#define FLOOPY_REGION_DISP			FLOOPY_OBJ+5
#define FLOOPY_REGION_BORDER		FLOOPY_OBJ+6
#define FLOOPY_REGION_OFFSET_BAR	FLOOPY_OBJ+7
#define FLOOPY_TRACKS_BORDER		FLOOPY_OBJ+8
#define FLOOPY_TRACK_BORDER			FLOOPY_OBJ+9


#endif // #ifndef ObjTypes_H
